### ISSUE TITLE
HAKAN ALTUN 3. HAFTA ÖDEVİ

### ISSUE THREAD

**Issue by HakanAltun1** [Pamir/bilgiuni-pyhton#50]
3. Hafta ödevi
 ll. hafta 4. soru düzelttim kontrol edermisiniz:
https://github.com/HakanAltun1/PHYTON/tree/master/WEEK3

**Comment by Pamir** [comment]
Hakan 3. hafta odevin eksik
ayrica duzeltiigin zaman o haftaki klasorde duzel odevbini week3 deyio icine week2 filan acma kafa karisiyir
