### ISSUE TITLE
CEMAYKAŞ:WEEK2

### ISSUE THREAD

**Issue by cem555** [Pamir/bilgiuni-pyhton#68]
Hocam merhabalar,

https://github.com/cem555/bilgiuni-pyhton/tree/master/week2

**Comment by Pamir** [comment]
ya abi neden benim repo'dan fork ediyorsun kendi reponu yaratacaksın !!!!! ben ona issue açacğım
ne yazık ki not veremiyorum şuan issue'yu da kapatıyorum
