### ISSUE TITLE
Anlaşılmayan Kısım

### ISSUE THREAD

**Issue by SedatOzdemir** [Pamir/bilgiuni-pyhton#8]
Merhabalar,
> Array e bölün tek sayı ise bir baştan bir sondan kontrol ederek ortanca elemena kadar gelin

Bu kısımda tek sayı ise derken neyi kastettiniz? Teşekkürler.

**Comment by Pamir** [comment]
Pamir 5 harfli tek sayi char array'in lengthi
abcdcba bu da tek sayı 7 karakter var. 
abcd çift 4 karakter var çift sayı
